### ISSUE TITLE
Pulling remote db not working

### ISSUE THREAD

**Issue by EvanHerman** [c10b10/wp-cli-deploy#27]
I am attempting to pull a remote database and replace my local instance with it.

`wp deploy pull production --what=db`

The command runs, and everything seems to go through successfully, but the database on my local instance doesn't actually update.

I can see that the files were pulled from my remote database fine and stored in a /production_*/ directory. So something seems to be going wrong during the replacement. Not sure where to begin looking.

**Comment by DavidCWebs** [comment]
Hi, you can get more info by adding `define('WP_DEPLOY_DEBUG', true);` to your config and repeating the pull.
Do you get a timestamped .sql file in your `/production_*/` directory?
I just tested it and I'm not seeing the downloaded database.

**Comment by EvanHerman** [comment]
@DavidCWebs,

I am getting the time stamped file but it's not importing properly. None of the table in my database updates. If I manually import the file using wp import db and specify that file, everything work fine. (Of course I still have to do a find and replace to update URLs).

With the WordPress deploy debug set to true, I see no errors during execution. Strange. I'll have to spend a little more time and see If can find anything else. As far as I know this project has been abandoned, so no future development will be taking place. I'm hoping it's just a setting on my end and nothing within the code itself.

**Comment by DavidCWebs** [comment]
Hi @EvanHerman 
What version of WP-CLI are you using?
What messages are you getting when it runs without debug turned on?
I've put myself forward to maintain this project but haven't been able to dig into it properly yet due to work pressure...I find it very useful so hopefully it's not abandoned!

**Comment by EvanHerman** [comment]
@davdcweds I'm running version 0.24.0. I'll take a second look and report back here with my debug report

**Comment by EvanHerman** [comment]
@DavidCWebs After doing some additional debugging, I was able to narrow down the issue to a few things. First, one of my paths was not set exactly right - so the file wasn't being generated server side.

The second issue, and a much larger one - my local site instance URL is set to http://local-site.dev , and my external site was set to https://www.external-site.com.

During the db import (search and replace) the URL was being improperly replaced. For example, when I pulled my remote DB, during the search and replace ` https://www.external-site.com` was being replaced with `www.external-site.com`.

I created a PR, which appends the scheme (http:// | https://) before returning the domain. It also checks that ['base'] is set and sanitizes the URL before returning it.

Not sure you have the power to merge things in, but the PR is there in case anyone else runs into a similar issue.

All this to say that a few issues were causing me problems, and it wasn't one specific thing.

**Comment by DavidCWebs** [comment]
Thanks @EvanHerman - sounds like a useful find on the search and replace. I'll check the PR this weekend.
